### PR TITLE
Fix typos and a critical error

### PR DESCRIPTION
**Pull request by szepeviktor**
Found misspellings.
While fixing them found a critical error.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Oh no!
This is more tricky then I thought.

https://github.com/spekulatius/PHPScraper/blob/b82f068d8af932a088378ae43e18acf7a80784ea/src/PHPScraper.php#L138-L140

Making a second commit ... 🏃🏻‍♂️

**Comment by szepeviktor** [comment]
❌ `NavigationTest::testSurfWithAbsoluteLink` fails as link on https://test-pages.phpscraper.de/navigation/1.html changed.

**Comment by spekulatius** [comment]
Hello @szepeviktor,

Thank you for your PR!

I've found the issue behind the tests failing: A setting for pretty URLs was active on Netlify. I've adjusted it and re-run the tests! Looks good! 

I've squashed and merged it :muscle: 

Cheers,
Peter

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
