### PR TITLE
Upgrading Symfony dependencies to allow ^7.0

### PR DESCRIPTION
**Pull request by tentacode**
Hello there and thanks for the scrapper, cant't wait to try it ! 👋

I could not install PHPScraper on a Symfony 7 project, I figured I'd just fork it.

I don't really know what you do expect as a contribution so don't hesitate to ask for more / redo it yourself or even close it, meanwhile I'm just using my fork and it works.

`composer install` and tests are passing on PHP 8.3 on my side

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @tentacode,

Thank you for your PR! Can you check the failing "Checks" and see if you can fix them?

Cheers,
Peter

**Comment by tentacode** [comment]
I upgraded rector to `^0.19`, there seem to be a dependency issue with phpstan that has been fixed meanwhile. Also run pint to fix coding standard, even though I don't know why the code was not ok. 🤷‍♂️

**Comment by tentacode** [comment]
ping @spekulatius :) if you can restart the workflow so that I can see if it's all ok 👌🙏

**Comment by spekulatius** [comment]
Thanks for the ping @tentacode , it's running :)

**Comment by spekulatius** [comment]
Looks good @tentacode! Thank you! I'll prepare a new release shortly.

**Comment by spekulatius** [comment]
Done, thank you @tentacode!

**Pull request merged**
